# Generated by Django 5.0.6 on 2024-06-27 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_landmark', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
                ('transport', models.CharField(choices=[('Автобус', 'Автобус'), ('Маршрутка', 'Маршрутка'), ('Такси', 'Такси')], max_length=32)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('hotel', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='GuideBookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Подтверждено', 'Подтверждено'), ('Отказ', 'Отказ'), ('Изменение', 'Изменение')], max_length=20)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guide')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='tours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.userprofile'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tour.userprofile'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=32)),
                ('restaurant', models.CharField(max_length=32)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('Бронировано', 'Бронировано'), ('Ожидание', 'Ожидание'), ('Отменено', 'Отменено')], max_length=20)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.landmark')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.userprofile')),
            ],
        ),
    ]
