# Generated by Django 5.0.6 on 2024-06-28 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_landmark_description_en_landmark_description_ky_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.landmark'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.tour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tour.userprofile'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='excursions',
            field=models.ManyToManyField(related_name='guides', to='tour.landmark'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='tours',
            field=models.ManyToManyField(related_name='guides', to='tour.tour'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to='tour.userprofile'),
        ),
        migrations.AlterField(
            model_name='guidebookingstatus',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_statuses', to='tour.guide'),
        ),
        migrations.AlterField(
            model_name='guidebookingstatus',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_statuses', to='tour.tour'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
