# Generated by Django 5.0.6 on 2024-06-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_booking_landmark_alter_booking_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebookingstatus',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.guide'),
        ),
        migrations.AlterField(
            model_name='guidebookingstatus',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
    ]
